name: Simple deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Setup node 20
        uses: actions/setup-node@v6
        with:
          node-version: "20"
      - name: Install dependency
        run: npm install
      - name: Check style
        run: npm run lint -w app/client
      - name: Build project
        run: npm run build -w app/client
      - name: commit list
        env:
          CHECK_COMMIT: ${{ github.event.commits[0].message }}
        run: echo "$CHECK_COMMIT"
      # - name: Deploy to render (Production)
      #   env:
      #     CHECK_SKIP: ${{ contains(github.event.commits[0].message,'#skip')  }}
      #   if: ${{github.event_name == 'push' && env.CHECK_SKIP != true  }}
      #   uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
      #   with:
      #     serviceId: ${{ secrets.RENDER_SERVICE_ID }}
      #     apiKey: ${{ secrets.RENDER_API_KEY }}
