name: Testing stuff
# sample comment
on:
  push:
    branches:
      - prTest

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: github context
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{toJson(github.event.commits)}}
        run: echo "$COMMITS"
      - name: commit message
        env:
          COMMIT_MESSAGES: ${{toJson(github.event.commits.*.message)}}
        run: echo "$COMMIT_MESSAGES"
      - name: check for skip commit
        env:
          CHECK_SKIP: ${{ contains(toJson(github.event.commits.message),'#skip')  }}
        run: echo "$CHECK_SKIP"
